namespace Mps.Infrastructure.Dependencies.Vnp_ay.Models
{
    public class VnPayRefundResponse
    {
        public string? Vnp_ResponseId { get; set; }       // Unique ID generated by the Vnp_AY system for each refund request.
        public string? Vnp_Command { get; set; }          // API command, which is "refund" for this transaction.
        public string? Vnp_TmnCode { get; set; }          // Merchant's unique identification code in the Vnp_AY system.
        public string? Vnp_TxnRef { get; set; }           // Payment transaction code from the merchant system.
        public decimal? Vnp_Amount { get; set; }          // Refund amount (in smallest currency unit).
        public string? Vnp_OrderInfo { get; set; }        // Content of the refund request.
        public string? Vnp_ResponseCode { get; set; }     // Response code indicating the status of the refund (00 means successful).
        public string? Vnp_Message { get; set; }          // Message corresponding to the response code.
        public string? Vnp_BankCode { get; set; }         // Bank or e-wallet code used for the payment.
        public string? Vnp_PayDate { get; set; }          // (Optional) Refund date (format: yyyyMMddHHmmss).
        public string? Vnp_TransactionNo { get; set; }    // Transaction code for the refund recorded in the Vnp_AY system.
        public string? Vnp_TransactionType { get; set; }  // Transaction type (02: Full refund, 03: Partial refund).
        public string? Vnp_TransactionStatus { get; set; } // Transaction status code in the Vnp_AY system.
        public string? Vnp_SecureHash { get; set; }       // Checksum to ensure data integrity.
    }
}
