namespace Mps.Infrastructure.Dependencies.Vnp_ay.Models
{
    public class VnPayRefundRequest
    {
        public string? Vnp_RequestId { get; set; }        // Unique ID generated by the merchant system for each refund request.
        public string Vnp_Version { get; set; } = "2.1.0"; // API version, the current version is 2.1.0.
        public string Vnp_Command { get; set; } = "refund"; // API command, which is "refund" for this transaction.
        public required string Vnp_TmnCode { get; set; }          // Merchant's unique identification code in the Vnp_AY system.
        public string? Vnp_TransactionType { get; set; }  // Transaction type (02: Full refund, 03: Partial refund).
        public required string Vnp_TxnRef { get; set; }           // Payment transaction code from the merchant system.
        public required decimal Vnp_Amount { get; set; }          // Refund amount (in smallest currency unit).
        public required string Vnp_OrderInfo { get; set; }        // Description of the refund request.
        public required string Vnp_TransactionNo { get; set; }    // (Optional) Transaction code recorded in the Vnp_AY system.
        public string? Vnp_TransactionDate { get; set; }  // Date and time of the transaction at the merchant website (format: yyyyMMddHHmmss).
        public string? Vnp_CreateBy { get; set; }         // Name of the user initiating the refund in the merchant system.
        public required string Vnp_CreateDate { get; set; }       // Date and time of the refund request (format: yyyyMMddHHmmss).
        public string? Vnp_IpAddr { get; set; }           // IP address of the server making the API call.
        public string? Vnp_SecureHash { get; set; }       // Checksum to ensure data integrity.
    }
}
